name: Kris
url: https://github.com/wangfagkui

menu:
  Home: /
  Archives: /archives/
  GitHub: https://github.com/wangfagkui
  RSS: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:

# Analytics
mathjax: false
google_analytics:

# Copyright Infomation
copyright:
  since: 2019
  name: Kris's Studio
  url:
